modLoader="javafml"
loaderVersion="[28,)" # Forge version
issueTrackerURL="https://github.com/svenhjol/Covalent/issues"
displayURL="https://svenhjol.github.io/Charm/"
#logoFile="examplemod.png"
#credits="Credits"

[[mods]]
modId="covalent"
version="${version}" #mandatory
displayName="Covalent"
description='''
Extra integration for Charm.
'''
authors="svenhjol"

[[dependencies.covalent]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.2,)" #mandatory
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER

[[dependencies.covalent]]
    modId="charm" #mandatory
    mandatory=true #mandatory
    versionRange="[1.15.2-1.5.9,)" #mandatory
    ordering="AFTER" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER